# Change these first
owner: cds-snc # Your GitHub organization or username, where this repository lives
repo: status-statut # The name of this repository

sites:
  - name: digital.canada.ca
    url: https://digital.canada.ca/
  - name: numerique.canada.ca
    url: https://numerique.canada.ca/
  - name: GC Articles - Articles GC
    url: https://articles.alpha.canada.ca/
  - name: GC Forms - Formulaires GC
    url: https://forms-formulaires.alpha.canada.ca/
  - name: GC Notify
    url: https://notification.canada.ca/
  - name: GC Notify API
    url: https://api.notification.canada.ca/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-statut
  logoUrl: https://raw.githubusercontent.com/cds-snc/status-statut/main/assets/cds-lockup-ko-en.svg
  name: CDS-SNC
  introTitle: "Canadian Digital Service / Service numérique canadien"
  introMessage: Status page for CDS products / Page de statut pour les produits du SNC
  navbar:
    - title: Status
      href: /status-statut
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
