# Change these first
owner: cds-snc # Your GitHub organization or username, where this repository lives
repo: status-statut # The name of this repository

sites:
  - name: digital.canada.ca
    url: https://digital.canada.ca/
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: numerique.canada.ca
    url: https://numerique.canada.ca/
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: GC Articles - Articles GC
    url: https://articles.alpha.canada.ca/sign-in-se-connecter/
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: GC Forms - Formulaires GC
    url: https://forms-formulaires.alpha.canada.ca/
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: GC Notify
    url: https://notification.canada.ca/
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: Scan websites
    url: https://scan-websites.alpha.canada.ca/
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: Scan files
    url: https://scan-files.alpha.canada.ca/healthcheck
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: Share encrypted messages
    url: https://encrypted-message.cdssandbox.xyz/
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: Share file securely
    url: https://share-files.cdssandbox.xyz/healthcheck
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: SRE Bot
    url: https://sre-bot.cdssandbox.xyz/version
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile
  - name: GitHub secret scanning
    url: https://github-secret-scanning.alpha.canada.ca/healthcheck
    assignees:
      - maxneuvians
      - CalvinRodo
      - patheard
      - dinophile

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-statut.cds-snc.ca
  # baseUrl: /status-statut
  logoUrl: https://raw.githubusercontent.com/cds-snc/status-statut/main/assets/cds-lockup-ko-en.svg
  name: ""
  introTitle: "Canadian Digital Service / Service numérique canadien"
  introMessage: Status page for CDS products / Page de statut pour les produits du SNC
  navbar:
    - title: Status / Statut
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Active Incidents / Incidents actifs
  allSystemsOperational: All systems are operational / Tous les systèmes sont opérationnels
  incidentReport: "Incident #$NUMBER report / Rapport d'incident #$NUMBER →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts / Ouvert à $DATE avec des postes $POSTS
  incidentTitle: Incident $NUMBER Details / Détails de l'incident $NUMBER
  incidentDetails: Incident Details / Détails de l'incident
  incidentFixed: Fixed / Fixé
  incidentOngoing: Ongoing / En cours
  incidentOpenedAt: Opened at / Ouvert à
  incidentClosedAt: Closed at / Fermé à
  incidentViewOnGitHub: View and Subscribe on GitHub / Voir et s'abonner sur GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR / Posté à $DATE par $AUTHOR
  incidentBack: ← Back to all incidents / Retour à tous les incidents
  pastIncidents: Past Incidents / Incidents passés
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts / Résolu en $MINUTES minutes avec les messages $POSTS
  liveStatus: Live Status / Statut en direct
  overallUptime: "Overall uptime / Temps de fonctionnement global: $UPTIME"
  overallUptimeTitle: Overall uptime / Temps de fonctionnement global
  averageResponseTime: "Average response time / Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Average response / Réponse moyenne
  sevelDayResponseTime: 7-day response time / Délai de réponse de 7 jours
  responseTimeMs: Response time (ms) / Temps de réponse (ms)
  up: Up / Opérationnel
  down: Down / En panne
  degraded: Degraded / Détérioré
  loading: Loading / Chargement
  footer: Canadian Digital Service / Service numérique canadien
  pastScheduledMaintenance: Past Scheduled Maintenance / Maintenance programmée passée
  scheduledMaintenance: Scheduled Maintenance / Maintenance programmée
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes / Démarré à $DATE pour $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes / Commence à $DATE pour $DURATION minutes
  startedAt: Started at / Commencé à
  startsAt: Starts at / Commence à
  duration: Duration / Durée
  durationMin: $DURATION minutes
  incidentCompleted: Completed / Complété
  incidentScheduled: Scheduled / Programmé
