apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: status-statut
  description: Status page for CDS products / Page de statut pour les produits du SNC
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
