name: Update workflows with PR
on:
  workflow_dispatch:
  pull_request:
jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                refs(refPrefix: "refs/tags/", first: 1, orderBy: {field: TAG_COMMIT_DATE, direction: DESC}) {
                  edges {
                    node {
                      name
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: "upptime",
              name: "uptime-monitor",
            }
            const result = await github.graphql(query, variables)
            const nodes = result.repository.refs.edges 
            const latest_tag = nodes[0].node.name
            console.log(latest_tag)