name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:
jobs:
  release:
    name: Check status
    runs-on: codebuild-cds-snc-status-statut-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check endpoint status
        uses: upptime/uptime-monitor@6996123d80fe861b66994b257d4e0eb99d9d7db6 # v1.40.1
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
