name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:
jobs:
  release:
    name: Check status
    runs-on: codebuild-cds-snc-status-statut-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check endpoint status
        uses: upptime/uptime-monitor@a9df8681951501693cbd6bea9c84df24bbf94210 # v1.43.16
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
